domain_path: /home/dushyant/vitis_prjcs/usb_ccid_test1_platform_comp/export/usb_ccid_test1_platform_comp/sw/standalone_psu_cortexa53_0
app_src_dir: /tools/Xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
